# Generated by Django 4.2.20 on 2025-03-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_title', models.CharField(max_length=300)),
                ('todo_content', models.TextField()),
                ('todo_priority', models.IntegerField(default=1)),
                ('todo_is_done', models.BooleanField()),
            ],
            options={
                'db_table': 'todos',
            },
        ),
    ]
